---

- hosts: last-try.org
  vars:
    stack_name: gitlab
    stack_dir: "{{ stack_dir_root }}/{{ stack_name }}"
    nfs_dir: "{{ nfs_swarm_fs_dir }}/{{ stack_name }}"
    stack_nfs_root: "{{ nfs_swarm_root }}/{{ stack_name }}"
  tasks:
    - name: Copy configs
      copy:
        src: "{{ stack_name }}/gitlab.rb"
        dest: "{{ stack_dir }}/gitlab.rb"
    - name: Create NFS dirs
      file:
        path: "/srv/nfs/docker-swarm/gitlab/{{ item }}"
        state: directory
        mode: "0777"
      become: yes
      with_items:
        - gitlab/data
        - gitlab/logs
        - gitlab/config
        - gitlab/backups
        - postgres
    - name: Copy secrets
      copy:
        src: "{{ stack_name }}/gitlab-secrets.json"
        dest: "/srv/nfs/docker-swarm/gitlab/gitlab/config/gitlab-secrets.json"
        mode: '0600'
    - name: Deploy GitLab
      docker_stack:
        state: present
        prune: true
        name: "{{ stack_name }}"
        compose:
          - version: "3.7"
            services:
              gitlab:
                image: gitlab/gitlab-ce:12.4.3-ce.0
                deploy:
                  restart_policy:
                    condition: any
                  placement:
                    constraints: [node.role == manager]
                  labels:
                    - traefik.enable=true
                    - traefik.http.services.gitlab-svc.loadbalancer.server.port=80
                    - traefik.http.services.registry-svc.loadbalancer.server.port=5003
                    - traefik.http.routers.gitlab.service=gitlab-svc
                    - traefik.http.routers.gitlab.rule=Host(`gitlab.last-try.org`)
                    - traefik.http.routers.gitlab.tls=true
                    - traefik.http.routers.gitlab.tls.certresolver=le
                    - traefik.http.routers.registry.service=registry-svc
                    - traefik.http.routers.registry.rule=Host(`registry.last-try.org`)
                    - traefik.http.routers.registry.tls=true
                    - traefik.http.routers.registry.tls.certresolver=le
                ports: # TODO move to TCP traefik
                  - target: 22
                    published: 10022
                    protocol: tcp
                    mode: ingress
                configs:
                  - source: "gitlab.rb"
                    target: "/etc/gitlab/gitlab.rb"
                volumes:
                  - gitlab_data:/var/opt/gitlab
                  - gitlab_logs:/var/log/gitlab
                  - gitlab_config:/etc/gitlab
                  - gitlab_backups:/var/opt/gitlab/backups
                networks:
                  - web
                  - default
                  # - smtp
              redis:
                deploy:
                  restart_policy:
                    condition: any
                image: "redis:4.0.6-alpine"
              postgres:
                deploy:
                  restart_policy:
                    condition: any
                image: "postgres:10.7-alpine"
                volumes:
                  - "postgres_data:/data"
                environment:
                  POSTGRES_USER: gitlab
                  POSTGRES_PASSWORD: gitlab
                  PGDATA: /data
                  POSTGRES_DB: gitlab

            volumes:
              gitlab_data:
                driver: local
                driver_opts:
                  type: nfs4
                  o: "addr={{ nfs_ip }}"
                  device: ":{{ stack_nfs_root }}/gitlab/data"
              gitlab_logs:
                driver: local
                driver_opts:
                  type: nfs4
                  o: "addr={{ nfs_ip }}"
                  device: ":{{ stack_nfs_root }}/gitlab/logs"
              gitlab_config:
                driver: local
                driver_opts:
                  type: nfs4
                  o: "addr={{ nfs_ip }}"
                  device: ":{{ stack_nfs_root }}/gitlab/config"
              gitlab_backups:
                driver: local
                driver_opts:
                  type: nfs4
                  o: "addr={{ nfs_ip }}"
                  device: ":{{ stack_nfs_root }}/gitlab/backups"
              postgres_data:
                driver: local
                driver_opts:
                  type: nfs4
                  o: "addr={{ nfs_ip }}"
                  device: ":{{ stack_nfs_root }}/postgres"

            configs:
              gitlab.rb:
                file: "{{ stack_dir }}/gitlab.rb"
            networks:
              web:
                external: true
              # smtp:
              #   external: true
